module MercadonaFX {
    requires javafx.graphics;
    requires javafx.controls;
    requires javafx.fxml;
    requires MaterialFX;

    requires lombok;
    requires com.google.gson;
    requires org.apache.logging.log4j;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.xml.bind;
    requires io.vavr;
    requires java.sql;
    requires org.yaml.snakeyaml;
    requires com.zaxxer.hikari;
    requires jakarta.annotation;
    requires spring.jdbc;
    requires spring.tx;

    exports ui;
    exports ui.common;
    exports ui.pantallas.pantallalogin;
    exports ui.pantallas.pantallamain;
    exports ui.pantallas.addarticlescreen;
    exports ui.pantallas.listarticlescreen;
    exports ui.pantallas.deletenewspaperscreen;
    exports ui.pantallas.listnewspaperscreen;
    exports ui.pantallas.listreaderscreen;
    exports ui.pantallas.deletereaderscreen;
    exports ui.pantallas.addreaderscreen;
    exports ui.pantallas.updatereaderscreen;
    exports ui.pantallas.addreadarticlescreen;
    exports ui.pantallas.addsubscriptionscreen;
    exports ui.pantallas.springqueryscreen;
    exports ui.pantallas.addnewspaperscreen;
    exports ui.pantallas.updatenewspaperscreen;
    exports ui.pantallas.common;
    exports servicios;
    exports config;
    exports data;
    exports di;
    exports model;

    opens model to javafx.base, com.google.gson, jakarta.xml.bind;
    opens config;
    opens servicios;
    opens data;
    opens common;
    opens ui;
    opens ui.common;
    opens data.common;
    opens ui.pantallas.pantallalogin to javafx.fxml;
    opens ui.pantallas.pantallamain to javafx.fxml;
    opens ui.pantallas.addarticlescreen to javafx.fxml;
    opens ui.pantallas.listarticlescreen to javafx.fxml;
    opens ui.pantallas.deletenewspaperscreen to javafx.fxml;
    opens ui.pantallas.listnewspaperscreen to javafx.fxml;
    opens ui.pantallas.listreaderscreen to javafx.fxml;
    opens ui.pantallas.deletereaderscreen to javafx.fxml;
    opens ui.pantallas.addreaderscreen to javafx.fxml;
    opens ui.pantallas.updatereaderscreen to javafx.fxml;
    opens ui.pantallas.addreadarticlescreen to javafx.fxml;
    opens ui.pantallas.addsubscriptionscreen to javafx.fxml;
    opens ui.pantallas.springqueryscreen to javafx.fxml;
    opens ui.pantallas.addnewspaperscreen to javafx.fxml;
    opens ui.pantallas.updatenewspaperscreen to javafx.fxml;
    opens ui.pantallas.common;
}